language: python
dist: precise
cache:
  - pip
python:
  - 3.5
install:
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - flake8 . --exclude manage.py,__pycache__,migrations --max-line-length=100
  - isort
